# Generated by Django 3.2.6 on 2021-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_auto_20210821_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order', '-timestamp']},
        ),
    ]
