# Generated by Django 3.2.6 on 2021-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='chetan', max_length=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=220),
        ),
    ]
