# Generated by Django 3.2.6 on 2021-08-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_name_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
    ]
